[project]
name = "langgraph-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kushal Kumar", email = "kjay45371@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.3.0",
    "langchain>=1.4.0",
    "langchain-core>=1.6.3",
    "langchain-google-genai>=2.0.0",
    "langchain-mistralai>=1.1.6",
    "langgraph>=1.2.11",
    "pydantic>=2.13.5",
    "rich>=15.0.0",
]

[project.scripts]
langgraph-tutorial = "langgraph_tutorial:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
